version: "3"

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    restart: always
    volumes:
      - .:/app
    ports:
      - "8082:8082" # Adjust port as neededs

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080" # Jenkins UI
      - "50000:50000" # Jenkins Slave
    volumes:
      - ./jenkins_home:/var/jenkins_home
